name: cs236781-hw
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.3.0
  - torchvision=0.4.1
  - ipython>=7.9
  - numpy
  - scikit-learn
  - cudatoolkit
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - ffmpeg>4.1
  - freetype>=2.10
  - pip
  - pip:
    - nbmerge
    - pytest-xdist
    - gym
    - atari-py
    - box2d-py

